/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Giovanni
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnMenuPrincipal = new javax.swing.JPanel();
        btLogin = new javax.swing.JButton();
        btFecharMnPrin = new javax.swing.JButton();
        cxSenha = new javax.swing.JTextField();
        rtSenha = new javax.swing.JLabel();
        rtUsuario = new javax.swing.JLabel();
        cxUsuario = new javax.swing.JTextField();
        comboCargo = new javax.swing.JComboBox<>();
        imgLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(410, 610));
        setResizable(false);

        PnMenuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btLogin.setBackground(new java.awt.Color(255, 255, 255));
        btLogin.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        btLogin.setForeground(new java.awt.Color(0, 0, 0));
        btLogin.setText("Entrar");
        btLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        PnMenuPrincipal.add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 260, 40));

        btFecharMnPrin.setBackground(new java.awt.Color(255, 255, 255));
        btFecharMnPrin.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        btFecharMnPrin.setForeground(new java.awt.Color(0, 0, 0));
        btFecharMnPrin.setText("Fechar");
        btFecharMnPrin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharMnPrinActionPerformed(evt);
            }
        });
        PnMenuPrincipal.add(btFecharMnPrin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, -1, -1));

        cxSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cxSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxSenhaActionPerformed(evt);
            }
        });
        PnMenuPrincipal.add(cxSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 260, 40));

        rtSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rtSenha.setForeground(new java.awt.Color(0, 0, 0));
        rtSenha.setText("Senha:");
        PnMenuPrincipal.add(rtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, 20));

        rtUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        rtUsuario.setText("Usuário:");
        PnMenuPrincipal.add(rtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 20));

        cxUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PnMenuPrincipal.add(cxUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 260, 40));

        comboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Chef", "Caixa", "Garçom", "Entregador" }));
        PnMenuPrincipal.add(comboCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 260, 40));

        imgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TelaLogin.jpg"))); // NOI18N
        PnMenuPrincipal.add(imgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharMnPrinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharMnPrinActionPerformed
        dispose();
    }//GEN-LAST:event_btFecharMnPrinActionPerformed

    private ConBD c = new ConBD();
    private ResultSet rst  = null;
    private ResultSet rstAux = null;
    
    
    public boolean verificLog(String cargo) throws SQLException{
        /*rst = null;
        rstAux = null;
        rst = c.OutBD("select login from funcionario where login = '"+ cxUsuario.getText()+"' and cargo = "+cargo+";");
        rst.next();
        rstAux = c.OutBD("select senha from funcionario where senha = '"+ cxSenha.getText()+"' and cargo = "+cargo+";");
        rstAux.next();
        if((cxUsuario.getText().equals(rst.getString(1))) && cxSenha.getText().equals(rstAux.getString(1))){
            return true;
        }else{
            return false;
        }*/
        
        if(c.TstBDStr("select coalesce((select login from funcionario where login = '"+cxUsuario.getText()+"' and cargo = '"+cargo+"' and senha = '"+ cxSenha.getText()+"' and ativo = true),'')") == true ){
            return true;
        }else{
            return false;
        }
        
        
    }
    
    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        boolean resp;
        switch (comboCargo.getSelectedIndex()) {
            case 0:
               // FuncGerente fg = new FuncGerente();
        
                try{
                   resp = verificLog("gerente");
                   if(resp){
                        MenuGerente mnGerente = new MenuGerente();
                        mnGerente.setVisible(true);
                        dispose();
                   }else{
                        JOptionPane.showMessageDialog(null, "Usuário ou Senha Incorretos","ERRO", 2);
                        cxSenha.setText("");
                        cxUsuario.setText("");
                    }
                }
                
                catch(NumberFormatException nfe){
                    JOptionPane.showMessageDialog(null, "Senha deve ser um Número","ERRO", 2);
                    cxSenha.setText("");
                } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
                
                break;

                
            case 1:
                //
                try{
                   resp = verificLog("chefe");
                   if(resp){
                        MenuChefe mnChefe = new MenuChefe();
                        mnChefe.setVisible(true);
                        dispose();
                   }else{
                        JOptionPane.showMessageDialog(null, "Usuário ou Senha Incorretos","ERRO", 2);
                        cxSenha.setText("");
                        cxUsuario.setText("");
                    }
                }
                
                catch(NumberFormatException nfe){
                    JOptionPane.showMessageDialog(null, "Senha deve ser um Número","ERRO", 2);
                    cxSenha.setText("");
                } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
                break;
                
            case 2:
                try {
                    resp = verificLog("caixa");
                    if (resp) {
                        MenuCaixa mnCaixa = new MenuCaixa();
                        mnCaixa.setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Usuário ou Senha Incorretos", "ERRO", 2);
                        cxSenha.setText("");
                        cxUsuario.setText("");
                    }
                } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(null, "Senha deve ser um Número", "ERRO", 2);
                    cxSenha.setText("");
                } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
                break;

                
            case 3:
                try {
                    resp = verificLog("garcom");
                    if (resp) {
                        MenuGarcom mnGarcom = new MenuGarcom();
                        mnGarcom.setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Usuário ou Senha Incorretos", "ERRO", 2);
                        cxSenha.setText("");
                        cxUsuario.setText("");
                    }
                } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(null, "Senha deve ser um Número", "ERRO", 2);
                    cxSenha.setText("");
                } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
                break;
                
            case 4:
                try {
                    resp = verificLog("motoboy");
                    if (resp) {
                        MenuMotoboy mnMotoboy = new MenuMotoboy();
                        mnMotoboy.setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Usuário ou Senha Incorretos", "ERRO", 2);
                        cxSenha.setText("");
                        cxUsuario.setText("");
                    }
                } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(null, "Senha deve ser um Número", "ERRO", 2);
                    cxSenha.setText("");
                } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
                break;
    
            default:
                JOptionPane.showMessageDialog(null, "Um cargo deve ser selecionado", "ERRO", 2);
                cxSenha.setText("");
                cxUsuario.setText("");
                break;
        }

    }//GEN-LAST:event_btLoginActionPerformed

    
    
    private void cxSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnMenuPrincipal;
    private javax.swing.JButton btFecharMnPrin;
    private javax.swing.JButton btLogin;
    private javax.swing.JComboBox<String> comboCargo;
    private javax.swing.JTextField cxSenha;
    private javax.swing.JTextField cxUsuario;
    private javax.swing.JLabel imgLogin;
    private javax.swing.JLabel rtSenha;
    private javax.swing.JLabel rtUsuario;
    // End of variables declaration//GEN-END:variables
}
