/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author Giovanni
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnMenuPrincipal = new javax.swing.JPanel();
        btLogin = new javax.swing.JButton();
        btMenuCliente = new javax.swing.JButton();
        btFecharMnPrin = new javax.swing.JButton();
        imgMenuPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(410, 610));
        setPreferredSize(new java.awt.Dimension(410, 610));
        setResizable(false);

        PnMenuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btLogin.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        btLogin.setText("Funcionário");
        btLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btLogin.setPreferredSize(new java.awt.Dimension(137, 33));
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        PnMenuPrincipal.add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 260, 40));

        btMenuCliente.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        btMenuCliente.setText("Cliente");
        btMenuCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuClienteActionPerformed(evt);
            }
        });
        PnMenuPrincipal.add(btMenuCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 260, 40));

        btFecharMnPrin.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        btFecharMnPrin.setText("Fechar");
        btFecharMnPrin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharMnPrinActionPerformed(evt);
            }
        });
        PnMenuPrincipal.add(btFecharMnPrin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, -1, -1));

        imgMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MenuPrincipal.jpg"))); // NOI18N
        PnMenuPrincipal.add(imgMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharMnPrinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharMnPrinActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btFecharMnPrinActionPerformed

    private void btMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuClienteActionPerformed
        MenuCliente menu = new MenuCliente();
        
        menu.setVisible(true);
    }//GEN-LAST:event_btMenuClienteActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        Login telaLogin = new Login();

        telaLogin.setVisible(true);
    }//GEN-LAST:event_btLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnMenuPrincipal;
    private javax.swing.JButton btFecharMnPrin;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btMenuCliente;
    private javax.swing.JLabel imgMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
